name: Build

on:
  push:
    branches: [ feature/updatable-status-window ]
  pull_request:
    branches: [ feature/updatable-status-window ]

jobs:
  build:

    runs-on: windows-2022

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore
      run: dotnet restore
    - name: Build
      run: .\make.bat
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: zip
        # path: build_installer\LenovoLegionToolkitSetup.exe
        path: |
          build