name: Release

on:
  push:
    tags:
      - "[0-9]*.[0-9]*.[0-9]*"

jobs:
  build:

    runs-on: windows-2022

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore
      run: dotnet restore
    - name: Build
      run: .\make.bat ${{ github.ref_name }}
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: LenovoLegionToolkitPortable.Release
        path: |
          build
